### PR TITLE
Feature: Message Builder for teamspeak bot

### PR DESCRIPTION
**Pull request by iHDeveloper**
# What's this future?
I want to implement a new way and easy one to build a message with color, bold and etc...
without do **[B]** and those confusing stuff.

# Usage
```javascript
const Builder = Alfred.Builder;

// @parm message that will be format
Builder.bold(message);
Builder.underline(message);
Builder.italic(message);

// @parm hex color that will color the message
Builder.color(hex, message);

// @parm clid Client ID EX: user.get("clid");
// @parm uid Client UID EX: user.get("uid");
// @parm name Name that will show into the message
Builder.client(clid, uid, name);

// @parm url The link of the URL that will open to the browser when someone clicks on it
// @parm text the text that will show in the message
Builder.url(url, text);
```
# What can it help?
It's can help developers to make the format so easily without having any trouble on it. And that's what your package goal is being easy to every developer who uses it.

### CODE REVIEW

**Comment by schroffl** [comment]
First of all, thank you very much for your contribution. I like the idea and I think it fits this package really well. Nonetheless, I would like to take a closer look at it later today and probably touch some things up.

Here's a small list of what I would change so far:

  - Replace `var` with `let` (especially in the documentation): It makes sense to get new developers accustomed to the block-scoped variable statements, since they behave more like most people would expect.
  - Add new lines to the files: You can see that they are missing by those [pesky little stop sings at the end of your diffs](https://github.com/schroffl/alfred-teamspeak/pull/7/commits/451ac0d851244159b3c4cdad16bf6c0fa4bd3fa9#diff-168726dbe96b3ce427e7fedce31bb0bcR5).

If you want you can do these changes yourself, otherwise I will take it on when I have the time. I don't know when exactly, though, because I'm currently planning to add [ssh support](https://github.com/schroffl/teamspeak-query/issues/13), which is coming with the next teamspeak server version, to [teamspeak-query](https://github.com/schroffl/teamspeak-query).

**Comment by iHDeveloper** [comment]
I'm so glad that you see my work. Also, don't worry about the changes. I can handle this and change them.

**Comment by iHDeveloper** [comment]
Here we go. I did those changes that you told me.
Also, I didn't understand the second change.

**Comment by schroffl** [comment]
Take a look at [this StackOverflow answer](https://stackoverflow.com/a/5813359/5516238). GitHub marks a missing last line ending with the little stop sign that I mentioned in [my previous comment](https://github.com/schroffl/alfred-teamspeak/pull/7#issuecomment-402475984), it's not that easy to see, but if you look closely you'll notice it.

**Comment by iHDeveloper** [comment]
```javascript
'use strict';

module.exports = require('./lib/index');
module.exports.User = require('./lib/user');
module.exports.Builder = require("./lib/builder");
 
```
like this ? You mean new line in the end?

**Comment by schroffl** [comment]
Basically, yes, in your editor/IDE there should be an empty last line visible.

**Comment by iHDeveloper** [comment]
I'm using VS-Code and when I save it clear the last lines.

**Comment by schroffl** [comment]
Oh ok, I will take care of it when merging :)

**Comment by iHDeveloper** [comment]
Thank you. If you need any help I can do my best. And what's the IDE that you are using it?

**Comment by schroffl** [comment]
I'm using Sublime Text (not really an IDE though), but please feel free to use whatever you want. If you like VS Code then by all means: use it :)

Also regarding the automatic removal: Are you sure that it's not some plugin you have installed? I find it hard to imagine that your editor just removes the last line. If it actually does, you can probably turn it off in the settings.

**Edit**: You might want to look at [this vscode issue](https://github.com/Microsoft/vscode/issues/30047).

**Comment by iHDeveloper** [comment]
There you go :). I had to use `Notepad++` instead of VS Code.

**Edit:** Thanks for the issue of vs code

**Comment by iHDeveloper** [comment]
I was bored and I check your library code and I found that there's no disconnect method for the query bot. So I made one hope it will be helpfully because it closes the connection so safety without any problems.

**Comment by schroffl** [comment]
I would prefer if we keep this separate. The message builder itself is a rather special topic, so it makes sense to have another pull request for other features like the disconnect method.

**Comment by iHDeveloper** [comment]
Okay, then I got some other features are ready for merge but I'm gonna wait till message builder got merged so things are not going out of hands.

**Comment by schroffl** [comment]
Can you please revert your last commit? The disconnect method would still get merged right now. Thank you :)

**Comment by iHDeveloper** [comment]
Okay lemme get my computer and do that. I will take it in a few hours.

**Comment by iHDeveloper** [comment]
Okay lemme get my computer and do that. I will take it in a few hours.

**Comment by iHDeveloper** [comment]
There you go, I reverted the commit.

**Edit:** I put docs into the functions so the developers will know what can they do with message builder.

**Comment by schroffl** [comment]
Hey, I have a suggestion for the API. Currently I have to build a full message like this:
```javascript
let u = Builder.bold('my bold text'),
    c = Builder.color('#ff0000', 'some red stuff'),
    msg = `Message: ${u} with ${c}.`;

// => msg = 'Message: [B]my bold text[/B] with [COLOR=#ff0000]some red stuff[/COLOR].'
```

But in my opinion it would be a lot nicer if you were able to chain the calls and it would automatically concatenate for you.
```javascript
let msg = Builder
  .text('Message: ').bold('my bold text')
  .text('with').color('#ff0000', 'some red stuff').text('.');
```

I'm not really sure though, what do you think about this?

**Comment by iHDeveloper** [comment]
Do you think it will be good if we make it with `.build()` or without it ?

**Comment by schroffl** [comment]
What exactly do you mean?

**Comment by iHDeveloper** [comment]
I mean in the end of formatting the whole message the developer should put `.build()` to make it to be string

**Comment by schroffl** [comment]
Oh, I would just overwrite the [`toString` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString). This way you automatically get the conversion when e.g. concatenating strings with `+`, etc.
But I'm still not really sure if I like what I proposed. I think your initial design was nicer. What do you say?

**Comment by iHDeveloper** [comment]
I tried to use it and it works! But it shows some deprecation warnings:
```
(node:8392) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
warning.js:18
(node:8392) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
```
The function that I'm using it is `build` * default function that calls to build prefix & suffix *
```js
function build(name, message) {
    let messageGotBuilt = prefix(name) + message + suffix(name);
    if (this.builder == null) {
        this.builder = new Object();
        this.builder.message = messageGotBuilt;
        this.builder.italic = italic;
        this.builder.underline = underline;
        this.builder.bold = bold;
        this.builder.client = client;
        this.builder.url = url;
        this.builder.color = color;
        this.builder.text = text;
        return this.builder;
    }
    this.builder.message += messageGotBuilt;
    return this.builder;
}
```

**Edit:** The IDE that I'm using says `[ts] This constructor function may be converted to a class declaration.`

**Comment by iHDeveloper** [comment]
Never mind I did it

**Comment by schroffl** [comment]
There's nothing in the code you posted that would trigger either warning. Other than that I would replace `new Object()` with `{}`.

**Comment by iHDeveloper** [comment]
```js
let builder = new Alfred.Builder("Hi");
builder.bold(" a ").underline("b").italic(" c ");
console.log(builder);
data.user.respond(builder);
```
**Edit:** Is this nicer then before ?

**Comment by schroffl** [comment]
> Is this nicer then before ?

What do you think? I still don't know if I prefer my suggestion, it doesn't really make it a lot easier than what you initially wrote.

**Comment by iHDeveloper** [comment]
It's the same as your suggestion. And I think yes.
```js
let msg = new Alfred.Builder('Message: ').bold('my bold text')
  .text('with').color('#ff0000', 'some red stuff').text('.');
user.respond(msg);
```

**Edit:** Use example from your suggestion.

**Comment by schroffl** [comment]
I meant to ask you if you actually prefer what I proposed in [this comment](https://github.com/schroffl/alfred-teamspeak/pull/7#issuecomment-403395678) or if you like your design, which you described [here](https://github.com/schroffl/alfred-teamspeak/pull/7#issue-199214637), more. I am asking because I am really unsure about it :)

**Comment by iHDeveloper** [comment]
With the new builder that I did. I test your code and I found that it works 100%

- The code in the test script
```js
let msg = new Alfred.Builder('Message: ').bold('my bold text')
            .text('with').color('#ff0000', 'some red stuff').text('.');
console.log(msg);
data.user.respond(msg);
```
- The result of that code in `console`;
```
Debugger listening on ws://127.0.0.1:49956/3fad6406-661c-4e6b-95af-a46e83348512

Connected with clid 10

null: Builder {message: "Message: [B]my bold text[/B]with[COLOR=#ff0000]som…"}
message: "Message: [B]my bold text[/B]with[COLOR=#ff0000]some red stuff[/COLOR]."
__proto__: Object {toString: , constructor: , build: , …}
```

- The result of that code in teamspeak [here](http://prntscr.com/k4adyk)

**Comment by schroffl** [comment]
Looks nice, but do you like the API? Do you think it is more usable than formatting every single part of the message separately and joining everything in the end like this:
```javascript
let u = Builder.bold('my bold text')
    c = Builder.color('#ff0000', 'some red stuff');

let msg = `Message: ${u} with ${c}`;
```

**Comment by iHDeveloper** [comment]
Look in that case I put both APIs into one. I mean the new one that I create is a class that exports from modules and the other methods which take every single part also exports from modules. In this case, the user of the API will be able to take all parts or single parts at the same time.

For example
```js
const Builder = Alfred.Builder;
let msg1 = new Alfred.Builder("Hey I have created from ").text("class");
let singlePart = Builder.bold("Single part");
let msg2 = `I have been created from ${singlePart}`;
```
So,Yeah the API will be useful because it gives the user a chance to do whatever he want.

**Comment by iHDeveloper** [comment]
I think we are ready to merge :)

**Comment by iHDeveloper** [comment]
bump

**Comment by schroffl** [comment]
I didn't forget about this, I just have to get something done this week and will get back to you tomorrow or on the weekend. Sorry for the inconvenience :/

**Comment by iHDeveloper** [comment]
It's fine

**Pull request merged**
